### ISSUE TITLE
Requested features | 已收集的建议

### ISSUE THREAD

**Issue by liulex** [liulex/Snipaste-Feedback#282]
Here summarizes all the requested features and would be kept updated. You can vote for them if you agree with any of it, though I don't promise they would all be implemented.

For discussion, please go the corresponding issues.

这里总结了已收集到的建议并将持续更新。你可以为它们投票，虽然我并不保证它们都会被实现。

欢迎到相应的 issue 补充你的观点或者提供任何帮助。

**Comment by liulex** [comment]
Plugin/script system
- pixel ruler
- Add custom border (shadow etc.) when saving to image
- Size annotation

**Comment by liulex** [comment]
- [ ] Plugin/script system # 250
  - [ ] Pixel ruler #203
  - [ ] Add custom border (shadow etc.) when saving to image #197
  - [ ] Size annotation #256

---

- [ ] 插件/脚本系统 # 250
  - [ ] 标尺 #203
  - [ ] 截图/贴图保存时添加外边框（如阴影等）#197
  - [ ] 尺寸标注 #256

**Comment by liulex** [comment]
- [ ] Plugin/script system # 250
  - [ ] Pixel ruler #203
  - [ ] Add custom border (shadow etc.) when saving to image #197
  - [ ] Size annotation #256

---

- [ ] 插件/脚本系统 # 250
  - [ ] 标尺 #203
  - [ ] 截图/贴图保存时添加外边框（如阴影等）#197
  - [ ] 尺寸标注 #256

**Comment by liulex** [comment]
~GIF 录制~
无计划，请使用 [LICEcap](http://www.cockos.com/licecap/) 或 [ScreenToGif](https://screentogif.codeplex.com) 等软件。

---

~GIF recording~
No plan. Please try [LICEcap](http://www.cockos.com/licecap/), [ScreenToGif](https://screentogif.codeplex.com), etc.

**Comment by liulex** [comment]
~Game screenshot~
No plan. Please use your games' built-in screenshot taking tools instead.

---

~游戏截屏~
无计划。请使用游戏自带的截屏功能。

**Comment by liulex** [comment]
- [ ] Scrolling window screenshot #19

---

- [ ] 滚动截屏/截长图 #19

**Comment by liulex** [comment]
- [ ] Open and edit image file directly, instead of its copy, via command line or context menu #16

---

- [ ] 以命令行方式/右键菜单方式支持直接编辑图像文件，而非副本 #16

**Comment by liulex** [comment]
- [ ] QR code reader #23

---

- [ ] 二维码识别 #23

**Comment by liulex** [comment]
- [ ] Input the area size when snipping #28
---
- [ ] 截图时可手动输入区域大小 #28

**Comment by liulex** [comment]
- [ ] Customize the action combination on screenshot done #38
---
- [ ] 自定义截图完成的动作组合 #38

**Comment by liulex** [comment]
- [ ] Move an image window to a preset position by hotkey #40
---
- [ ] 通过快捷键将贴图移动到指定位置 #40

**Comment by liulex** [comment]
- [ ] When an image(s) file is selected, press the hotkey for paster to pin it to screen #44
---
- [ ] 选中文件的时候，按贴图键直接贴出选中文件 #44

**Comment by liulex** [comment]
- [ ] Stitch images of multiple windows to one #45
---
- [ ] 多个贴图拼接 #45

**Comment by liulex** [comment]
- [ ] Save the current image group to some folder #54
---
- [ ] 贴图组另存为 #54

**Comment by liulex** [comment]
- [ ] Customize the zoom scale for the magnifier #56
---
- [ ] 自定义放大镜倍数 #56

**Comment by liulex** [comment]
- [ ] Image upload/share #60
---
- [ ] 图片上传/分享 #60

**Comment by liulex** [comment]
- [ ] Copy image as file #78
---
- [ ] 截图/贴图复制为文件 #78

**Comment by liulex** [comment]
- [ ] Allow to set the background color of annotation / the outline color for text #83
---
- [ ] 设置背景色、文字描边颜色 #83

**Comment by liulex** [comment]
- [ ] Dashline annotation #92
---
- [ ] 虚线标注 #92

**Comment by liulex** [comment]
- [ ] Convert image to grey scale #127
---
- [ ] 贴图转灰度图像 #127

**Comment by liulex** [comment]
- [ ] Try to copy gif in an animation format #156
---
- [ ] 尝试以动图格式复制 gif #156

**Comment by liulex** [comment]
- [ ] Send image to an external image editor #159
---
- [ ] 图片发送到外部编辑器 #159

**Comment by liulex** [comment]
- [ ] Program name blacklist for global hotkeys #84 #160
---
- [ ] 全局快捷键黑名单 #84 #160

**Comment by liulex** [comment]
- [ ] Try to handle html format with web images #161
---
- [ ] 贴图尝试处理含网络图片的 html 格式 #161

**Comment by liulex** [comment]
- [ ] Optimize website access speed for snipaste's official site #162
---
- [ ] 优化官网访问速度 #162

**Comment by liulex** [comment]
- [ ] Specify the color depth when saving an image #163
---
- [ ] 设置图片保存时的颜色深度 #163

**Comment by liulex** [comment]
- [ ] Add download links for history versions on website #170
---
- [ ] 官网添加历史版本下载链接 #170

**Comment by liulex** [comment]
- [ ] Pause global hotkeys #171
---
- [ ] 暂停全局热键 #171

**Comment by liulex** [comment]
- [ ] Do not quit snipping when a screenshot is taken and saved, so as to take sequential screenshots #173
---
- [ ] 截图完成后不退出，以连续截图 #173

**Comment by liulex** [comment]
- [ ] Align the image windows to some pattern #183
---
- [ ] 贴图自动排列 #183

**Comment by liulex** [comment]
- [ ] Optical Character Recognition #188
---
- [ ] OCR 文字识别 #188

**Comment by liulex** [comment]
- [ ] Zoom-in annotation #193
---
- [ ] 局部放大镜标注 #193

**Comment by liulex** [comment]
- [ ] Compress the image before sent to clipboard #201
---
- [ ] 压缩复制到剪贴板中的图像 #201

**Comment by liulex** [comment]
- [ ] Allow to set mouse click-through state for an individual image window #206
---
- [ ] 对单个贴图设置鼠标穿透 #206

**Comment by liulex** [comment]
- [ ] Sort, preview the image groups #223
---
- [ ] 贴图组排序、预览 #223

**Comment by liulex** [comment]
- [ ] Copy the image path after it's saved to file #225
---
- [ ] 图片被保存后自动复制其路径 #225

**Comment by liulex** [comment]
- [ ] Number marking #227
---
- [ ] 计数标注 #227

**Comment by liulex** [comment]
- [ ] Color groups #234
---
- [ ] 颜色组 #234

**Comment by liulex** [comment]
- [ ] Customize how to display the alpha channel of images #239
---
- [ ] 自定义贴图透明通道显示效果 #239

**Comment by liulex** [comment]
- [ ] Embed ICC Profile into image #239
---
- [ ] ICC Profile 内嵌支持 #239

**Comment by liulex** [comment]
- [ ] Zoom image at mouse cursor #277
---
- [ ] 以鼠标位置为中心缩放贴图 #277

**Comment by liulex** [comment]
- [ ] Customize the actions on entering snipping #283
---
- [ ] 自定义进入截图的组合动作 #283

**Comment by liwanglin12** [comment]
@liulex ocr一票

**Comment by liulex** [comment]
- [ ] 'Reset image' also works in thumbnail mode #280 
---
- [ ] 重置贴图操作对缩略图也起作用 #280

**Comment by liulex** [comment]
- [ ] Record more then one snipped area and switch between them by pressing multiple times of <kbd>R</kbd>/<kbd>Shift</kbd> + <kbd>R</kbd>  #249
---
- [ ] 记录多个历史截图区域，通过多次按下 <kbd>R</kbd>/<kbd>Shift</kbd> + <kbd>R</kbd> 进行切换 #249

**Comment by grs432** [comment]
现在已有截图的区域滚动截图，我测试的是一个网页中嵌入的滚动页面，几乎没有完美的，我测试了Snagit 13和HyperSnap v8.12。都不完美，截不到底部，区域太小，不完整。不知道是不是我使用的方式不对，不过我觉得这个可以加入开发，难度方面不知道怎样。

**Comment by liulex** [comment]
- [ ] Allow to independently resize the thumbnail #284
--
- [ ] 允许自由调整缩略图状态的贴图大小 #284

**Comment by liulex** [comment]
v1.11.0
- [x] Whiteboard mode #150
---
- [x] 白板模式 #150

**Comment by liulex** [comment]
- [ ] Cycle through history snipping areas
---
- [ ] 循环选择历史截图区域

**Comment by liulex** [comment]
- [ ] Arbitrary pen width  #276
---
- [ ] 连续调整画笔粗细 #276

**Comment by liulex** [comment]
- [ ] Add scrollbars to the image window
---
- [ ] 贴图增加滚动条

**Comment by cloudinsky** [comment]
截图粘贴自带水印的功能.

提前设置好水印(简单点都OK了)

每次粘贴,自带水印上去.

**Comment by liulex** [comment]
[ ] Allow to resize images in thumbnail mode #284

---

 [ ] 自由调整缩略图状态的贴图大小 #284

**Comment by liulex** [comment]
- [ ] Enhance 'Send to printer' #324

---

- [ ] 增强“发送到打印机” #324

**Comment by liulex** [comment]
- [ ] Adapt to virtual desktop #328

---

- [ ] 适配虚拟桌面 #328

**Comment by liulex** [comment]
- [ ] Provide a fast way to adjust the transparency of annotation #338

---

- [ ] 快速调整标注的透明度 #338

**Comment by liulex** [comment]
- [ ] Customize what to reset when resetting the image window #340

---

- [ ] 自定义贴图重置的行为 #340

**Comment by liulex** [comment]
- [ ] Add visual hints when aligning an image window to the border of another window #341

---

- [ ] 贴图对齐提示 #341

**Comment by liulex** [comment]
- [ ] Support multi-selection of image windows #345

---

- [ ] 贴图多选 #345

**Comment by liulex** [comment]
v1.12
 
- [x] Let the cursor icon reveal the pen size #352

---

- [x] 光标图案体现画笔粗细 #352

**Comment by liulex** [comment]
- [ ] Allow to set the DPI of output image #357

---

- [ ] 允许设置输出图像的 DPI #357

**Comment by liulex** [comment]
v1.12
 
- [x] Customize the page margin for image-to-text conversion #359

---

- [x] 自定义文字转图片的边距 #359

**Comment by liulex** [comment]
Pro
 
- [x] Allow to navigate into the parent/child element when detecting UI elements #362

---

- [x] 检测界面元素时可切换至当前元素的父/子元素 #362

**Comment by liulex** [comment]
v1.12
 
- [x] Support environment variables in folder paths #367

---

- [x] 存储路径支持环境变量 #367

**Comment by ganghaoyujianni** [comment]
贴到屏幕Ctrl+T 每次都需要两个手按不太方便 可否自己设置快捷键

**Comment by GregAMO** [comment]
@ganghaoyujianni 顶部说明：

欢迎到相应的 issue 补充你的意见或者提供任何帮助。但请不要在此帖下面留言，所有留言会被立即删除。

**Comment by hackasc** [comment]
需要OCR的场景：有些地方的文字是不能复制的，比如某些软件说明，比如某些网站，某些字幕...而有些地方最好粘贴文字。我经常遇到那种XX，给我发的截图很长，在手机上简直没法看的情况...或者给我截的图在显示器上看没问题，但是用手机看要划拉半天，还可能会看错行，而回复他有需要知道这里面的细节！真是疯了。

**Comment by SJTUboy** [comment]
希望Mac开发进度条能够变成95%，加油加油！！

**Comment by KanGuoqiang** [comment]
mac的80%半年了。。。

**Comment by nightkall** [comment]
Reverse image Google search option like Lightshot would be awesome. Thanks for this amazing tool, very well designed ;D

**Comment by wpapp** [comment]
一个滚动截图，另一个编辑的功能再多一些，就可以跟FSC说不再见了。

**Comment by BianChengNan** [comment]
有两个需求,请考虑下:
1. 不要限制延后截屏的时间(现在貌似是1.0-10.0) ,解除限制没有什么副作用, 限制了反而造成了一些不便.
比如,有一个设置 我需要很长时间才能找到,10秒不够用...

2.能否把文字的透明度和矩形区域的透明度分开?绝大多数情况下我希望文字是不透明的,而我现在喜欢用半透明框选区域,框选完区域后,如果需要添加文字的话,总是需要切换不透明度,很不方便
btw,有没有快捷键,可以快速输入文字,框选区域.
![snipaste_2018-04-18_14-05-27](https://user-images.githubusercontent.com/5259514/38914341-95e891fc-4311-11e8-94cc-1b3bcca50039.png)

**Comment by BianChengNan** [comment]
@liulex 额,为啥我新写的feature request被删掉了...

**Comment by liulex** [comment]
@BianChengNan 仔细读一读一楼内容？

**Comment by GHLandy** [comment]
> Linux version development progress:
> 
> * 40%
> 
> Linux 版开发进度:
> 
> * 40%

Linux 版本的现在开发进度如何了？已经停止了吗？

**Comment by wpdu** [comment]
添加OCR识别，截图后，功能选项增加一个OCR识别的按钮，可以识别基本的文字，字符，数字就行

**Comment by lesvers** [comment]
请问可以增加类似“隐藏 menu icon”的选项么？

**Comment by sfire** [comment]
> Linux version development progress:
> 
> * 40%
> 
> Linux 版开发进度:
> 
> * 40%



> Linux version development progress:
> 
> * 40%
> 
> Linux 版开发进度:
> 
> * 40%

等linux版好久了，但一直没看到进展。
最近发现一款类似的软件[flameshot](https://github.com/lupoDharkael/flameshot) ,不过用起来手感没有snipaste舒服。
我觉得可以参考一下他的代码把Linux版尽快整出来。^_^

**Comment by zombie110year** [comment]
> 等linux版好久了，但一直没看到进展。
> 最近发现一款类似的软件[flameshot](https://github.com/lupoDharkael/flameshot) ,不过用起来手感没有snipaste舒服。
> 我觉得可以参考一下他的代码把Linux版尽快整出来。^_^

作者做的是商业软件，得考虑协议。

**Comment by FanXiangTM** [comment]
是否会增加OCR功能

**Comment by rain298** [comment]
Linux 版本取消开发了吗？

**Comment by satcon** [comment]
希望新增选择 【笔尖】 选项：圆头笔、凿头笔，可参考win10 截图工具

**Comment by FanXiangTM** [comment]
在截图状态下，按“C”键取色，默认把RGB数值复制到剪切板，建议改为默认复制HEX编码，或者增加自定义默认复制剪切板选项，而不需要每次按F3再到右键去复制。实际使用的使用户中HEX编码更常用

**Comment by SengerLee** [comment]
最近QQ截图新上了一个“序号笔工具”的功能，希望Snipaste也能加上，谢谢
